build:
    before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    script:
        - ./build.sh
    after_script:
        - docker logout
    when: always
    only:
        refs:
            - master
    tags:
        - docker

check:
    when: always
    only:
        - schedules
    script:
        - ./generate.php
        - changes=$(git status --porcelain | wc -l)
        - if [ ${changes} -gt 0 ]; then exit 1; else exit 0; fi
    tags:
        - php
